<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>cz.cvut.kbss.benchmark</groupId>
    <artifactId>otm-benchmark</artifactId>
    <packaging>pom</packaging>
    <version>0.0.6</version>
    <name>OTM Benchmark</name>
    <description>Performance/memory benchmark of object-triple mapping (OTM) libraries.</description>

    <modules>
        <module>core</module>
        <module>alibaba-benchmark</module>
<!--        <module>empire-benchmark</module>-->
        <module>jopa-benchmark</module>
        <module>komma-benchmark</module>
        <module>rdfbeans-benchmark</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
    </properties>

    <repositories>
        <repository>
            <id>KBSS</id>
            <url>https://kbss.felk.cvut.cz/m2repo</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>cz.cvut.kbss.benchmark</groupId>
            <artifactId>benchmark-runner</artifactId>
            <version>0.1.0</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.11.2</version>
        </dependency>
    </dependencies>


    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
            </plugin>

            <!-- Set project version (recursively) -->
            <!-- Usage mvn versions:set -DnewVersion=$version and then mvn versions:commit to confirm changes -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>versions-maven-plugin</artifactId>
                <version>2.7</version>
            </plugin>
        </plugins>
    </build>
</project>
